
name: Verificación de Ejercicios Python

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  check-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar flake8
        run: pip install flake8

      - name: Verificar errores de sintaxis
        run: python -m py_compile 101_ejercicios.py

      - name: Ejecutar flake8
        run: flake8 101_ejercicios.py --max-line-length=100
